---
# Binary Sensor Configuration
binary_sensor:

  # Touch state
  - platform: template
    name: Touch
    id: touch
    internal: false

  #  Physical hardware button below display to toggle relay
  - platform: gpio
    name: Button Left
    id: button_left
    pin:
      number: 14
      inverted: true
    on_press:
      then:
        - lambda: |-
            id(publish_event).execute("button_left", "1");
    on_release:
      then:
        - lambda: |-
            id(publish_event).execute("button_left", "0");
    on_click:
      if:
        condition:
        - switch.is_on: use_relay_left
        then:
        - switch.toggle: relay_left


  # Physical hardware button below display to toggle relay
  - platform: gpio
    name: Button Right
    id: button_right
    pin:
      number: 27
      inverted: true
    on_press:
      then:
        - lambda: |-
            id(publish_event).execute("button_right", "1");
    on_release:
      then:
        - lambda: |-
            id(publish_event).execute("button_right", "0");
    on_click:
      if:
        condition:
        - switch.is_on: use_relay_right
        then:
        - switch.toggle: relay_right
