---
# Sensor Configuration
sensor:

  # Current page
  # this sensor will get updated when a page change event occured
  - platform: template
    name: Page
    id: page
    internal: true # don't expose too much updates
    accuracy_decimals: 0
    update_interval: never
    on_value:
      then:
        - lambda: |-
            id(publish_event).execute("page", to_string((uint8_t)x));

  # Touch X coordinates
  - platform: nextion
    nextion_id: haui_disp
    name: "Touch X"
    id: touch_x
    variable_name: tch0
    update_interval: 100ms
    accuracy_decimals: 0
    internal: true # don't expose too much updates
    filters:
      # Allow to pass the value only if the value changed
      - lambda: |-
          if (id(touch_x).state != x) {
            return x;
          } else {
            return {};
          }

  # Touch Y coordinates
  - platform: nextion
    nextion_id: haui_disp
    name: "Touch Y"
    id: touch_y
    variable_name: tch1
    update_interval: 100ms
    accuracy_decimals: 0
    internal: true # don't expose too much updates
    filters:
      # Allow to pass the value only if the value changed
      - lambda: |-
          if (id(touch_y).state != x) {
            return x;
          } else {
            return {};
          }

  # Brightness of display
  - platform: nextion
    nextion_id: haui_disp
    id: brightness
    name: Brightness
    internal: true  # don't expose too much updates
    accuracy_decimals: 0
    update_interval: 100ms
    variable_name: dim
    filters:
      - lambda: |-
          if (id(brightness).state != x) {
            return x;
          } else {
            return {};
          }

  # Last Interaction
  - platform: template
    name: Last Interaction
    id: last_interaction
    update_interval: never
    accuracy_decimals: 0
    internal: true  # don't expose too much updates
    on_value:
        - lambda: |-
            id(update_last_interaction).execute(x, 0);

  # Uptime
  - platform: uptime
    name: Uptime
    disabled_by_default: true

  # WIFI Signal stregth
  - platform: wifi_signal
    name: RSSI
    update_interval: 60s

  # Internal temperature sensor, ADC value
  - platform: adc
    name: ADC
    id: ntc_source
    pin: 38
    update_interval: 60s
    attenuation: 12db
    entity_category: diagnostic
    disabled_by_default: true

  # Internal temperature sensor
  # ADC reading converted to resistance (calculation)
  - platform: resistance
    name: Resistance
    id: resistance_sensor
    sensor: ntc_source
    entity_category: diagnostic
    configuration: DOWNSTREAM
    resistor: 11.2kOhm
    disabled_by_default: true

  # Internal temperature sensor
  # resistance to temperature (calculation)
  - platform: ntc
    name: Temperature
    id: temperature
    sensor: resistance_sensor
    calibration:
      b_constant: 3950
      reference_temperature: 25°C
      reference_resistance: 10kOhm
    filters:
      # add offset to value
      - lambda: return x + id(temperature_correction).state;
