#
# Configuration for NSPanel HomeAssistant UI
#

# The substituions will be defined in the install.yaml.
# this file should not be directly edited.

substitutions:
  # General config
  heartbeat_interval: $heartbeat_interval
  friendly_name: $frindly_name
  name: $name
  mqtt_name: $mqtt_name
  # MQTT config
  mqtt_ip: $mqtt_ip
  mqtt_username: $mqtt_username
  mqtt_password: $mqtt_password
  topic_prefix: $topic_prefix
  topic_cmd: $topic_cmd
  topic_recv: $topic_recv
  # Accounts and Passwords
  ota_password: $ota_password
  api_encryption_key: $api_encryption_key
  web_username: $web_username
  web_password: $web_password
  wifi_ssid: $wifi_ssid
  wifi_password: $wifi_password
  ap_password: $ap_password
  # Custom Update Url
  tft_update_url: $tft_update_url

packages:
  version: !include nspanel_haui/version.yaml
  globals: !include nspanel_haui/globals.yaml
  base: !include nspanel_haui/base.yaml
  device: !include nspanel_haui/device.yaml
  display: !include nspanel_haui/display.yaml
  interval: !include nspanel_haui/interval.yaml
  script: !include nspanel_haui/script.yaml
  mqtt: !include nspanel_haui/mqtt.yaml
  api: !include nspanel_haui/api.yaml
  button: !include nspanel_haui/button.yaml
  number: !include nspanel_haui/number.yaml
  switch: !include nspanel_haui/switch.yaml
  sensor: !include nspanel_haui/sensor.yaml
