#
# Configuration for NSPanel HomeAssistant UI
#

# Config Variables
substitutions:

  # Heartbeat interval in seconds
  heartbeat_interval: '5'
  # Friendly name of the device
  friendly_name: 'NSPanel HAUI'
  # Name of the device (mqtt device name should match device name,
  # use only underscore in mqtt device name)
  name: nspanel-haui  # this name is also used for hostname
  mqtt_device_name: nspanel_haui

  # MQTT config
  mqtt_ip: !secret mqtt_ip
  mqtt_username: !secret mqtt_username
  mqtt_password: !secret mqtt_password
  topic_prefix: nspanel_haui/$mqtt_device_name
  topic_cmd: $topic_prefix/cmd  # used for sending events
  topic_recv: $topic_prefix/recv  # used to recieve events

  # Accounts and Passwords
  ota_password: !secret ota_password
  api_encryption_key: !secret api_encryption_key
  web_username: !secret web_username
  web_password: !secret web_password
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  ap_password: !secret ap_password

  # Custom Update Url
  tft_update_url: https://github.com/happydasch/nspanel_haui/raw/master/device/nspanel_haui.tft
  #tft_update_url: http://homeassistant.local:8123/local/nspanel/nspanel_haui.tft

packages:
  version: !include nspanel_haui/version.yaml
  globals: !include nspanel_haui/globals.yaml
  base: !include nspanel_haui/base.yaml
  device: !include nspanel_haui/device.yaml
  display: !include nspanel_haui/display.yaml
  interval: !include nspanel_haui/interval.yaml
  script: !include nspanel_haui/script.yaml
  mqtt: !include nspanel_haui/mqtt.yaml
  api: !include nspanel_haui/api.yaml
  button: !include nspanel_haui/button.yaml
  number: !include nspanel_haui/number.yaml
  switch: !include nspanel_haui/switch.yaml
  sensor: !include nspanel_haui/sensor.yaml
  binary_sensor: !include nspanel_haui/binary_sensor.yaml
  text_sensor: !include nspanel_haui/text_sensor.yaml