name: Validate

on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master, dev]
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions: {}

jobs:
  hassfest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: home-assistant/actions/hassfest@master

  hacs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: hacs/action@main
        with:
          category: integration
